import { Inter } from 'next/font/google';
import Navbar from '../components/navbar/Navbar';
import './globals.css';
import { Providers } from "./providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'APDCC | ASOCIACIÓN DE PROFESIONALES DOCENTES DE CLUBES DE CAMPO',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark bg-background text-foreground`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
